<div class="pl-80 pr-80 pt-5">

  <div>
    <div class="p-6 mt-5  bg-stone-200 ">
<h1 class=" text-center text-2xl">Añadir una tarea</h1>
</div>

<div class="bg-sky-100 p-14">
<form method="post" class= "w-full">
 <div>
  <label>Nombre tarea</label>
  <div>
  <input type="text" id="nombre" name="nombre" class="w-full mt-1 p-2"><br><br>
  </div>
  <label>Fecha inicio</label>
  <div>
  <input datepicker type="text" id="finicio" name="f_inicio" class="w-full mt-1 p-2"><br><br>
  </div>
  <label>Fecha fin</label>
  <div>
  <input datepicker type="text" id="ffin" name="f_fin" class="w-full mt-1 p-2"><br><br>
  </div>
  <label>Creador</label>
  <div>
  <input type="text" id="creador" name="creador" class="w-full mt-1 p-2"><br><br>
  </div>
  <div class="pt-2">
  <label class="pr-3">Estado</label>
<select name="estado" id="estado" class=" p-2">
  <option value="pendiente">Pendiente</option>
  <option value="ejecucion">En ejecución</option>
  <option value="terminada">Terminada</option></select><br><br>
</div>

<div class="pt-10">
  <input type="submit" value="Añadir tarea" class="bg-orange-400 hover:bg-orange-500 pt-3 pb-3 pl-5 pr-5 text-white rounded mr-3">  <a href="../web/"><input type="button" value="Volver" class="bg-blue-500 hover:bg-blue-600 pt-3 pb-3 pl-5 pr-5 text-white rounded"></a></div>
</div>
</form>
</div>

  </div>


</div>
