<header class="pb-16">
  <div class="md:flex md:justify-between bg-gradient-to-r from-cyan-500 to-blue-500 px-10 py-6 w-full">
    <div class="flex justify-center">
      <a href="../web/">
        <img src="images/logo-task.png" width="180px" height="96px" alt="TODO App" >
      </a>
    </div>
    <div class=" hidden md:flex self-center w-33 h-12 p-3 rounded-lg bg-orange-400 font-semibold text-red-50 hover:bg-orange-500">
      <a href="../web/add" > <i class="fa-solid fa-circle-plus"></i></i><span class="pl-2 uppercase">nueva tarea</span>
    </a>
    </div>
  </div>
  <div class=" md:hidden w-33 h-12 self-end bg-orange-400 p-3 text-center font-semibold text-red-50 hover:bg-orange-500">
      <a href="../web/add"> <i class="fa-solid fa-circle-plus"></i></i><span class="pl-2 uppercase">nueva tarea</span>
    </a>
  </div>
</header>